### ISSUE TITLE
Issue with extra_hosts in docker-compose

### ISSUE THREAD

**Issue by chriswiggins** [resin-io/resin-supervisor#661]
Hi guys,

Not sure whether this belongs here or under **balena** so let me know if I should move it.

I'm trying to add extra_hosts into my compose file however I'm being thrown errors when the service is started on the device.

Running `Resin OS 2.12.5+rev2` and Supervisor `7.1.18`

Logs from dashboard:

```
17.05.18 17:33:11 (+1200) Failed to install service 'dind sha256:27813baba31ea28b5b25fbcfe8212012f62239aec7138c50a9947ad2feb93155' due to '(HTTP code 500) server error - json: cannot unmarshal object into Gostruct field HostConfig.ExtraHosts of type []string '
```

logs from `balena logs -f resin_supervisor`
```
[2018-05-17T05:33:41.252Z] Scheduling another update attempt due to failure:  30000 { Error: (HTTP code 500) server error - json: cannot unmarshal object into Go struct field HostConfig.ExtraHosts of type []string
    at /usr/src/app/dist/app.js:545:103361
    at /usr/src/app/dist/app.js:545:103324
    at m.buildPayload (/usr/src/app/dist/app.js:545:103334)
    at IncomingMessage.<anonymous> (/usr/src/app/dist/app.js:545:102834)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
  reason: 'server error',
  statusCode: 500,
  json: { message: 'json: cannot unmarshal object into Go struct field HostConfig.ExtraHosts of type []string' } }
[2018-05-17T05:33:41.253Z] Apply error Error: (HTTP code 500) server error - json: cannot unmarshal object into Go struct field HostConfig.ExtraHosts of type []string
```

Here is the relevant `extra_hosts` config (changed for security)
```
  dind:
    build: ./dind
    restart: always
    privileged: true
    volumes:
      - dind:/var/lib/docker
    extra_hosts:
      - "private.docker.host:10.1.2.3"
    network_mode: "host"
    depends_on:
      - openvpn
```

Any ideas on what could be causing this?
Cheers
